### ISSUE TITLE
Crear issues con estructura proyecto

### ISSUE THREAD

**Issue by craciunescu** [ubiqcomp/capacity#4]
#### Os dejo esto aquí de recordatorio para crear los issues que le den la estructura principal al proyecto. No os olvidéis de configurar correctamente las opciones en la barra de la derecha! Un saludo a todos 🚀

**PD: Os incito a echarle un ojo al formatting de markdown. Es una herramienta muy potente que tiene infinidad de usos hoy en día! [Os dejo un link con más información sobre ello](https://guides.github.com/features/mastering-markdown/)**

---
### Checklist
- [x] [Introducción](https://github.com/ubiqcomp/capacity/issues/3)
- [x] [Análisis del Problema](https://github.com/ubiqcomp/capacity/issues/5)
- [x] [Objetivos y Scope del Proyecto escogido](https://github.com/ubiqcomp/capacity/issues/2)
- [x] [Descripción de ideas descartadas](https://github.com/ubiqcomp/capacity/issues/1)
- [x] [Tecnología que usar](https://github.com/ubiqcomp/capacity/issues/6)
- [x] [Planificación temporal, plan de desarrollo](https://github.com/ubiqcomp/capacity/issues/7)
- [x] [Resumen y conclusiones del proyecto](https://github.com/ubiqcomp/capacity/issues/8)

**Comment by HernandezIgnacio** [comment]
He estado haciendo los issues [Análisis del Problema](#5) y [Objetivos y Scope del Proyecto escogido](#2). Cuando podáis, por favor, echadles un vistazo para ver que todo esté correcto.

**Comment by craciunescu** [comment]
@ZainAzhar @RobertPetrisor aseguraos de que los issues que habéis creado están bien linkeados en el comentario original. Echadle un ojo a cómo lo ha hecho @HernandezIgnacio con los suyos. Cuando lo tengáis, podéis pasar el issue a la columna de "A la espera de revisión".

Un saludo y buen trabajo

**Comment by craciunescu** [comment]
@ZainAzhar @RobertPetrisor recordatorio de poner los links bien. Si no, no podemos cerrar este issue.
